// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bobmodel

import (
	"context"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
)

// HealthCheck is an object representing the database table.
type HealthCheck struct {
	ID        int64     `db:"id,pk" `
	CreatedAt time.Time `db:"created_at" `
	Note      string    `db:"note" `
}

// HealthCheckSlice is an alias for a slice of pointers to HealthCheck.
// This should almost always be used instead of []*HealthCheck.
type HealthCheckSlice []*HealthCheck

// HealthChecks contains methods to work with the health_check table
var HealthChecks = psql.NewTablex[*HealthCheck, HealthCheckSlice, *HealthCheckSetter]("", "health_check", buildHealthCheckColumns("health_check"))

// HealthChecksQuery is a query on the health_check table
type HealthChecksQuery = *psql.ViewQuery[*HealthCheck, HealthCheckSlice]

func buildHealthCheckColumns(alias string) healthCheckColumns {
	return healthCheckColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "created_at", "note",
		).WithParent("health_check"),
		tableAlias: alias,
		ID:         psql.Quote(alias, "id"),
		CreatedAt:  psql.Quote(alias, "created_at"),
		Note:       psql.Quote(alias, "note"),
	}
}

type healthCheckColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         psql.Expression
	CreatedAt  psql.Expression
	Note       psql.Expression
}

func (c healthCheckColumns) Alias() string {
	return c.tableAlias
}

func (healthCheckColumns) AliasedAs(alias string) healthCheckColumns {
	return buildHealthCheckColumns(alias)
}

// HealthCheckSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type HealthCheckSetter struct {
	ID        omit.Val[int64]     `db:"id,pk" `
	CreatedAt omit.Val[time.Time] `db:"created_at" `
	Note      omit.Val[string]    `db:"note" `
}

func (s HealthCheckSetter) SetColumns() []string {
	vals := make([]string, 0, 3)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.Note.IsValue() {
		vals = append(vals, "note")
	}
	return vals
}

func (s HealthCheckSetter) Overwrite(t *HealthCheck) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.Note.IsValue() {
		t.Note = s.Note.MustGet()
	}
}

func (s *HealthCheckSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return HealthChecks.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 3)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[1] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Note.IsValue() {
			vals[2] = psql.Arg(s.Note.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s HealthCheckSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s HealthCheckSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 3)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.Note.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "note")...),
			psql.Arg(s.Note),
		}})
	}

	return exprs
}

// FindHealthCheck retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindHealthCheck(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*HealthCheck, error) {
	if len(cols) == 0 {
		return HealthChecks.Query(
			sm.Where(HealthChecks.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return HealthChecks.Query(
		sm.Where(HealthChecks.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(HealthChecks.Columns.Only(cols...)),
	).One(ctx, exec)
}

// HealthCheckExists checks the presence of a single record by primary key
func HealthCheckExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return HealthChecks.Query(
		sm.Where(HealthChecks.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after HealthCheck is retrieved from the database
func (o *HealthCheck) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = HealthChecks.AfterSelectHooks.RunHooks(ctx, exec, HealthCheckSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = HealthChecks.AfterInsertHooks.RunHooks(ctx, exec, HealthCheckSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = HealthChecks.AfterUpdateHooks.RunHooks(ctx, exec, HealthCheckSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = HealthChecks.AfterDeleteHooks.RunHooks(ctx, exec, HealthCheckSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the HealthCheck
func (o *HealthCheck) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *HealthCheck) pkEQ() dialect.Expression {
	return psql.Quote("health_check", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the HealthCheck
func (o *HealthCheck) Update(ctx context.Context, exec bob.Executor, s *HealthCheckSetter) error {
	v, err := HealthChecks.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single HealthCheck record with an executor
func (o *HealthCheck) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := HealthChecks.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the HealthCheck using the executor
func (o *HealthCheck) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := HealthChecks.Query(
		sm.Where(HealthChecks.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after HealthCheckSlice is retrieved from the database
func (o HealthCheckSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = HealthChecks.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = HealthChecks.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = HealthChecks.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = HealthChecks.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o HealthCheckSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("health_check", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o HealthCheckSlice) copyMatchingRows(from ...*HealthCheck) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o HealthCheckSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return HealthChecks.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *HealthCheck:
				o.copyMatchingRows(retrieved)
			case []*HealthCheck:
				o.copyMatchingRows(retrieved...)
			case HealthCheckSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a HealthCheck or a slice of HealthCheck
				// then run the AfterUpdateHooks on the slice
				_, err = HealthChecks.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o HealthCheckSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return HealthChecks.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *HealthCheck:
				o.copyMatchingRows(retrieved)
			case []*HealthCheck:
				o.copyMatchingRows(retrieved...)
			case HealthCheckSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a HealthCheck or a slice of HealthCheck
				// then run the AfterDeleteHooks on the slice
				_, err = HealthChecks.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o HealthCheckSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals HealthCheckSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := HealthChecks.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o HealthCheckSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := HealthChecks.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o HealthCheckSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := HealthChecks.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}
