// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bobmodel

import (
	"context"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
)

// SchemaMigration is an object representing the database table.
type SchemaMigration struct {
	ID        int32     `db:"id,pk" `
	VersionID int64     `db:"version_id" `
	IsApplied bool      `db:"is_applied" `
	Tstamp    time.Time `db:"tstamp" `
}

// SchemaMigrationSlice is an alias for a slice of pointers to SchemaMigration.
// This should almost always be used instead of []*SchemaMigration.
type SchemaMigrationSlice []*SchemaMigration

// SchemaMigrations contains methods to work with the schema_migrations table
var SchemaMigrations = psql.NewTablex[*SchemaMigration, SchemaMigrationSlice, *SchemaMigrationSetter]("", "schema_migrations", buildSchemaMigrationColumns("schema_migrations"))

// SchemaMigrationsQuery is a query on the schema_migrations table
type SchemaMigrationsQuery = *psql.ViewQuery[*SchemaMigration, SchemaMigrationSlice]

func buildSchemaMigrationColumns(alias string) schemaMigrationColumns {
	return schemaMigrationColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "version_id", "is_applied", "tstamp",
		).WithParent("schema_migrations"),
		tableAlias: alias,
		ID:         psql.Quote(alias, "id"),
		VersionID:  psql.Quote(alias, "version_id"),
		IsApplied:  psql.Quote(alias, "is_applied"),
		Tstamp:     psql.Quote(alias, "tstamp"),
	}
}

type schemaMigrationColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         psql.Expression
	VersionID  psql.Expression
	IsApplied  psql.Expression
	Tstamp     psql.Expression
}

func (c schemaMigrationColumns) Alias() string {
	return c.tableAlias
}

func (schemaMigrationColumns) AliasedAs(alias string) schemaMigrationColumns {
	return buildSchemaMigrationColumns(alias)
}

// SchemaMigrationSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type SchemaMigrationSetter struct {
	ID        omit.Val[int32]     `db:"id,pk" `
	VersionID omit.Val[int64]     `db:"version_id" `
	IsApplied omit.Val[bool]      `db:"is_applied" `
	Tstamp    omit.Val[time.Time] `db:"tstamp" `
}

func (s SchemaMigrationSetter) SetColumns() []string {
	vals := make([]string, 0, 4)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.VersionID.IsValue() {
		vals = append(vals, "version_id")
	}
	if s.IsApplied.IsValue() {
		vals = append(vals, "is_applied")
	}
	if s.Tstamp.IsValue() {
		vals = append(vals, "tstamp")
	}
	return vals
}

func (s SchemaMigrationSetter) Overwrite(t *SchemaMigration) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.VersionID.IsValue() {
		t.VersionID = s.VersionID.MustGet()
	}
	if s.IsApplied.IsValue() {
		t.IsApplied = s.IsApplied.MustGet()
	}
	if s.Tstamp.IsValue() {
		t.Tstamp = s.Tstamp.MustGet()
	}
}

func (s *SchemaMigrationSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return SchemaMigrations.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 4)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.VersionID.IsValue() {
			vals[1] = psql.Arg(s.VersionID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.IsApplied.IsValue() {
			vals[2] = psql.Arg(s.IsApplied.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Tstamp.IsValue() {
			vals[3] = psql.Arg(s.Tstamp.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s SchemaMigrationSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s SchemaMigrationSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 4)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.VersionID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "version_id")...),
			psql.Arg(s.VersionID),
		}})
	}

	if s.IsApplied.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "is_applied")...),
			psql.Arg(s.IsApplied),
		}})
	}

	if s.Tstamp.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "tstamp")...),
			psql.Arg(s.Tstamp),
		}})
	}

	return exprs
}

// FindSchemaMigration retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindSchemaMigration(ctx context.Context, exec bob.Executor, IDPK int32, cols ...string) (*SchemaMigration, error) {
	if len(cols) == 0 {
		return SchemaMigrations.Query(
			sm.Where(SchemaMigrations.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return SchemaMigrations.Query(
		sm.Where(SchemaMigrations.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(SchemaMigrations.Columns.Only(cols...)),
	).One(ctx, exec)
}

// SchemaMigrationExists checks the presence of a single record by primary key
func SchemaMigrationExists(ctx context.Context, exec bob.Executor, IDPK int32) (bool, error) {
	return SchemaMigrations.Query(
		sm.Where(SchemaMigrations.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after SchemaMigration is retrieved from the database
func (o *SchemaMigration) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = SchemaMigrations.AfterSelectHooks.RunHooks(ctx, exec, SchemaMigrationSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = SchemaMigrations.AfterInsertHooks.RunHooks(ctx, exec, SchemaMigrationSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = SchemaMigrations.AfterUpdateHooks.RunHooks(ctx, exec, SchemaMigrationSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = SchemaMigrations.AfterDeleteHooks.RunHooks(ctx, exec, SchemaMigrationSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the SchemaMigration
func (o *SchemaMigration) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *SchemaMigration) pkEQ() dialect.Expression {
	return psql.Quote("schema_migrations", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the SchemaMigration
func (o *SchemaMigration) Update(ctx context.Context, exec bob.Executor, s *SchemaMigrationSetter) error {
	v, err := SchemaMigrations.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single SchemaMigration record with an executor
func (o *SchemaMigration) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := SchemaMigrations.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the SchemaMigration using the executor
func (o *SchemaMigration) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := SchemaMigrations.Query(
		sm.Where(SchemaMigrations.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after SchemaMigrationSlice is retrieved from the database
func (o SchemaMigrationSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = SchemaMigrations.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = SchemaMigrations.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = SchemaMigrations.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = SchemaMigrations.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o SchemaMigrationSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("schema_migrations", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o SchemaMigrationSlice) copyMatchingRows(from ...*SchemaMigration) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o SchemaMigrationSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return SchemaMigrations.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *SchemaMigration:
				o.copyMatchingRows(retrieved)
			case []*SchemaMigration:
				o.copyMatchingRows(retrieved...)
			case SchemaMigrationSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a SchemaMigration or a slice of SchemaMigration
				// then run the AfterUpdateHooks on the slice
				_, err = SchemaMigrations.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o SchemaMigrationSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return SchemaMigrations.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *SchemaMigration:
				o.copyMatchingRows(retrieved)
			case []*SchemaMigration:
				o.copyMatchingRows(retrieved...)
			case SchemaMigrationSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a SchemaMigration or a slice of SchemaMigration
				// then run the AfterDeleteHooks on the slice
				_, err = SchemaMigrations.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o SchemaMigrationSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals SchemaMigrationSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := SchemaMigrations.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o SchemaMigrationSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := SchemaMigrations.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o SchemaMigrationSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := SchemaMigrations.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}
